spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:587

kafka:
  broker:
    host: localhost:9092
  topics:
    notification-topic:
      name: notification-topic
      group-id: group-id
    account-topic:
      name: account-topic
      group-id: group-id-2

account-confirmation-url: "http://localhost:8080/auth/confirm?token="

server:
  port: 8083