spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: lb://${PRODUCT_SERVICE_URI:product-service}
          predicates:
            - Path=/product/**
          filters:
            - PrefixPath=/api

        - id: user-service-auth-login-route
          uri: lb://${USER_SERVICE_URI:user-service}
          predicates:
            - Method=POST
            - Path=/auth/**
          filters:
            - PrefixPath=/api

        - id: order-service-route
          uri: lb://${ORDER_SERVICE_URI:order-service}
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/api

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 8080