spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/order
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null

info:
  app:
    description: Order Service

kafka:
  topics:
    notification-topic: notification-topic

server:
  port: 8084

