spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
      username: user
      password: password
  jackson:
    default-property-inclusion: non_null

server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

jwt:
  public-key: ${PUBLIC_KEY}


