version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54321:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local